package com.ylk.datamineservice.model;

import java.util.Date;

public class AreaInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.id
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.parentId
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.orgType
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private String orgtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.orgCode
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private String orgcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.orgName
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private String orgname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.orgAddr
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private String orgaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.orgLinkMan
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private String orglinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.orgLinkTel
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private String orglinktel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.cardPwd
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private String cardpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.electricityPrice
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Integer electricityprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.memo
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.state
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.deleted
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.createTime
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.updateTime
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.createBy
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_org.updateBy
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Integer updateby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.id
     *
     * @return the value of ylk_org.id
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.id
     *
     * @param id the value for ylk_org.id
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.parentId
     *
     * @return the value of ylk_org.parentId
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.parentId
     *
     * @param parentid the value for ylk_org.parentId
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.orgType
     *
     * @return the value of ylk_org.orgType
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public String getOrgtype() {
        return orgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.orgType
     *
     * @param orgtype the value for ylk_org.orgType
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setOrgtype(String orgtype) {
        this.orgtype = orgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.orgCode
     *
     * @return the value of ylk_org.orgCode
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.orgCode
     *
     * @param orgcode the value for ylk_org.orgCode
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.orgName
     *
     * @return the value of ylk_org.orgName
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.orgName
     *
     * @param orgname the value for ylk_org.orgName
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.orgAddr
     *
     * @return the value of ylk_org.orgAddr
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public String getOrgaddr() {
        return orgaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.orgAddr
     *
     * @param orgaddr the value for ylk_org.orgAddr
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setOrgaddr(String orgaddr) {
        this.orgaddr = orgaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.orgLinkMan
     *
     * @return the value of ylk_org.orgLinkMan
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public String getOrglinkman() {
        return orglinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.orgLinkMan
     *
     * @param orglinkman the value for ylk_org.orgLinkMan
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setOrglinkman(String orglinkman) {
        this.orglinkman = orglinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.orgLinkTel
     *
     * @return the value of ylk_org.orgLinkTel
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public String getOrglinktel() {
        return orglinktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.orgLinkTel
     *
     * @param orglinktel the value for ylk_org.orgLinkTel
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setOrglinktel(String orglinktel) {
        this.orglinktel = orglinktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.cardPwd
     *
     * @return the value of ylk_org.cardPwd
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public String getCardpwd() {
        return cardpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.cardPwd
     *
     * @param cardpwd the value for ylk_org.cardPwd
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setCardpwd(String cardpwd) {
        this.cardpwd = cardpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.electricityPrice
     *
     * @return the value of ylk_org.electricityPrice
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Integer getElectricityprice() {
        return electricityprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.electricityPrice
     *
     * @param electricityprice the value for ylk_org.electricityPrice
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setElectricityprice(Integer electricityprice) {
        this.electricityprice = electricityprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.memo
     *
     * @return the value of ylk_org.memo
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.memo
     *
     * @param memo the value for ylk_org.memo
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.state
     *
     * @return the value of ylk_org.state
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.state
     *
     * @param state the value for ylk_org.state
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.deleted
     *
     * @return the value of ylk_org.deleted
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.deleted
     *
     * @param deleted the value for ylk_org.deleted
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.createTime
     *
     * @return the value of ylk_org.createTime
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.createTime
     *
     * @param createtime the value for ylk_org.createTime
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.updateTime
     *
     * @return the value of ylk_org.updateTime
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.updateTime
     *
     * @param updatetime the value for ylk_org.updateTime
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.createBy
     *
     * @return the value of ylk_org.createBy
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.createBy
     *
     * @param createby the value for ylk_org.createBy
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_org.updateBy
     *
     * @return the value of ylk_org.updateBy
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_org.updateBy
     *
     * @param updateby the value for ylk_org.updateBy
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }
}