package com.ylk.datamineservice.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AreaInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public AreaInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParentidIsNull() {
            addCriterion("parentId is null");
            return (Criteria) this;
        }

        public Criteria andParentidIsNotNull() {
            addCriterion("parentId is not null");
            return (Criteria) this;
        }

        public Criteria andParentidEqualTo(Integer value) {
            addCriterion("parentId =", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotEqualTo(Integer value) {
            addCriterion("parentId <>", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThan(Integer value) {
            addCriterion("parentId >", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThanOrEqualTo(Integer value) {
            addCriterion("parentId >=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThan(Integer value) {
            addCriterion("parentId <", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThanOrEqualTo(Integer value) {
            addCriterion("parentId <=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidIn(List<Integer> values) {
            addCriterion("parentId in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotIn(List<Integer> values) {
            addCriterion("parentId not in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidBetween(Integer value1, Integer value2) {
            addCriterion("parentId between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotBetween(Integer value1, Integer value2) {
            addCriterion("parentId not between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andOrgtypeIsNull() {
            addCriterion("orgType is null");
            return (Criteria) this;
        }

        public Criteria andOrgtypeIsNotNull() {
            addCriterion("orgType is not null");
            return (Criteria) this;
        }

        public Criteria andOrgtypeEqualTo(String value) {
            addCriterion("orgType =", value, "orgtype");
            return (Criteria) this;
        }

        public Criteria andOrgtypeNotEqualTo(String value) {
            addCriterion("orgType <>", value, "orgtype");
            return (Criteria) this;
        }

        public Criteria andOrgtypeGreaterThan(String value) {
            addCriterion("orgType >", value, "orgtype");
            return (Criteria) this;
        }

        public Criteria andOrgtypeGreaterThanOrEqualTo(String value) {
            addCriterion("orgType >=", value, "orgtype");
            return (Criteria) this;
        }

        public Criteria andOrgtypeLessThan(String value) {
            addCriterion("orgType <", value, "orgtype");
            return (Criteria) this;
        }

        public Criteria andOrgtypeLessThanOrEqualTo(String value) {
            addCriterion("orgType <=", value, "orgtype");
            return (Criteria) this;
        }

        public Criteria andOrgtypeLike(String value) {
            addCriterion("orgType like", value, "orgtype");
            return (Criteria) this;
        }

        public Criteria andOrgtypeNotLike(String value) {
            addCriterion("orgType not like", value, "orgtype");
            return (Criteria) this;
        }

        public Criteria andOrgtypeIn(List<String> values) {
            addCriterion("orgType in", values, "orgtype");
            return (Criteria) this;
        }

        public Criteria andOrgtypeNotIn(List<String> values) {
            addCriterion("orgType not in", values, "orgtype");
            return (Criteria) this;
        }

        public Criteria andOrgtypeBetween(String value1, String value2) {
            addCriterion("orgType between", value1, value2, "orgtype");
            return (Criteria) this;
        }

        public Criteria andOrgtypeNotBetween(String value1, String value2) {
            addCriterion("orgType not between", value1, value2, "orgtype");
            return (Criteria) this;
        }

        public Criteria andOrgcodeIsNull() {
            addCriterion("orgCode is null");
            return (Criteria) this;
        }

        public Criteria andOrgcodeIsNotNull() {
            addCriterion("orgCode is not null");
            return (Criteria) this;
        }

        public Criteria andOrgcodeEqualTo(String value) {
            addCriterion("orgCode =", value, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeNotEqualTo(String value) {
            addCriterion("orgCode <>", value, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeGreaterThan(String value) {
            addCriterion("orgCode >", value, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeGreaterThanOrEqualTo(String value) {
            addCriterion("orgCode >=", value, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeLessThan(String value) {
            addCriterion("orgCode <", value, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeLessThanOrEqualTo(String value) {
            addCriterion("orgCode <=", value, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeLike(String value) {
            addCriterion("orgCode like", value, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeNotLike(String value) {
            addCriterion("orgCode not like", value, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeIn(List<String> values) {
            addCriterion("orgCode in", values, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeNotIn(List<String> values) {
            addCriterion("orgCode not in", values, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeBetween(String value1, String value2) {
            addCriterion("orgCode between", value1, value2, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgcodeNotBetween(String value1, String value2) {
            addCriterion("orgCode not between", value1, value2, "orgcode");
            return (Criteria) this;
        }

        public Criteria andOrgnameIsNull() {
            addCriterion("orgName is null");
            return (Criteria) this;
        }

        public Criteria andOrgnameIsNotNull() {
            addCriterion("orgName is not null");
            return (Criteria) this;
        }

        public Criteria andOrgnameEqualTo(String value) {
            addCriterion("orgName =", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotEqualTo(String value) {
            addCriterion("orgName <>", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameGreaterThan(String value) {
            addCriterion("orgName >", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameGreaterThanOrEqualTo(String value) {
            addCriterion("orgName >=", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLessThan(String value) {
            addCriterion("orgName <", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLessThanOrEqualTo(String value) {
            addCriterion("orgName <=", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLike(String value) {
            addCriterion("orgName like", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotLike(String value) {
            addCriterion("orgName not like", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameIn(List<String> values) {
            addCriterion("orgName in", values, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotIn(List<String> values) {
            addCriterion("orgName not in", values, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameBetween(String value1, String value2) {
            addCriterion("orgName between", value1, value2, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotBetween(String value1, String value2) {
            addCriterion("orgName not between", value1, value2, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgaddrIsNull() {
            addCriterion("orgAddr is null");
            return (Criteria) this;
        }

        public Criteria andOrgaddrIsNotNull() {
            addCriterion("orgAddr is not null");
            return (Criteria) this;
        }

        public Criteria andOrgaddrEqualTo(String value) {
            addCriterion("orgAddr =", value, "orgaddr");
            return (Criteria) this;
        }

        public Criteria andOrgaddrNotEqualTo(String value) {
            addCriterion("orgAddr <>", value, "orgaddr");
            return (Criteria) this;
        }

        public Criteria andOrgaddrGreaterThan(String value) {
            addCriterion("orgAddr >", value, "orgaddr");
            return (Criteria) this;
        }

        public Criteria andOrgaddrGreaterThanOrEqualTo(String value) {
            addCriterion("orgAddr >=", value, "orgaddr");
            return (Criteria) this;
        }

        public Criteria andOrgaddrLessThan(String value) {
            addCriterion("orgAddr <", value, "orgaddr");
            return (Criteria) this;
        }

        public Criteria andOrgaddrLessThanOrEqualTo(String value) {
            addCriterion("orgAddr <=", value, "orgaddr");
            return (Criteria) this;
        }

        public Criteria andOrgaddrLike(String value) {
            addCriterion("orgAddr like", value, "orgaddr");
            return (Criteria) this;
        }

        public Criteria andOrgaddrNotLike(String value) {
            addCriterion("orgAddr not like", value, "orgaddr");
            return (Criteria) this;
        }

        public Criteria andOrgaddrIn(List<String> values) {
            addCriterion("orgAddr in", values, "orgaddr");
            return (Criteria) this;
        }

        public Criteria andOrgaddrNotIn(List<String> values) {
            addCriterion("orgAddr not in", values, "orgaddr");
            return (Criteria) this;
        }

        public Criteria andOrgaddrBetween(String value1, String value2) {
            addCriterion("orgAddr between", value1, value2, "orgaddr");
            return (Criteria) this;
        }

        public Criteria andOrgaddrNotBetween(String value1, String value2) {
            addCriterion("orgAddr not between", value1, value2, "orgaddr");
            return (Criteria) this;
        }

        public Criteria andOrglinkmanIsNull() {
            addCriterion("orgLinkMan is null");
            return (Criteria) this;
        }

        public Criteria andOrglinkmanIsNotNull() {
            addCriterion("orgLinkMan is not null");
            return (Criteria) this;
        }

        public Criteria andOrglinkmanEqualTo(String value) {
            addCriterion("orgLinkMan =", value, "orglinkman");
            return (Criteria) this;
        }

        public Criteria andOrglinkmanNotEqualTo(String value) {
            addCriterion("orgLinkMan <>", value, "orglinkman");
            return (Criteria) this;
        }

        public Criteria andOrglinkmanGreaterThan(String value) {
            addCriterion("orgLinkMan >", value, "orglinkman");
            return (Criteria) this;
        }

        public Criteria andOrglinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("orgLinkMan >=", value, "orglinkman");
            return (Criteria) this;
        }

        public Criteria andOrglinkmanLessThan(String value) {
            addCriterion("orgLinkMan <", value, "orglinkman");
            return (Criteria) this;
        }

        public Criteria andOrglinkmanLessThanOrEqualTo(String value) {
            addCriterion("orgLinkMan <=", value, "orglinkman");
            return (Criteria) this;
        }

        public Criteria andOrglinkmanLike(String value) {
            addCriterion("orgLinkMan like", value, "orglinkman");
            return (Criteria) this;
        }

        public Criteria andOrglinkmanNotLike(String value) {
            addCriterion("orgLinkMan not like", value, "orglinkman");
            return (Criteria) this;
        }

        public Criteria andOrglinkmanIn(List<String> values) {
            addCriterion("orgLinkMan in", values, "orglinkman");
            return (Criteria) this;
        }

        public Criteria andOrglinkmanNotIn(List<String> values) {
            addCriterion("orgLinkMan not in", values, "orglinkman");
            return (Criteria) this;
        }

        public Criteria andOrglinkmanBetween(String value1, String value2) {
            addCriterion("orgLinkMan between", value1, value2, "orglinkman");
            return (Criteria) this;
        }

        public Criteria andOrglinkmanNotBetween(String value1, String value2) {
            addCriterion("orgLinkMan not between", value1, value2, "orglinkman");
            return (Criteria) this;
        }

        public Criteria andOrglinktelIsNull() {
            addCriterion("orgLinkTel is null");
            return (Criteria) this;
        }

        public Criteria andOrglinktelIsNotNull() {
            addCriterion("orgLinkTel is not null");
            return (Criteria) this;
        }

        public Criteria andOrglinktelEqualTo(String value) {
            addCriterion("orgLinkTel =", value, "orglinktel");
            return (Criteria) this;
        }

        public Criteria andOrglinktelNotEqualTo(String value) {
            addCriterion("orgLinkTel <>", value, "orglinktel");
            return (Criteria) this;
        }

        public Criteria andOrglinktelGreaterThan(String value) {
            addCriterion("orgLinkTel >", value, "orglinktel");
            return (Criteria) this;
        }

        public Criteria andOrglinktelGreaterThanOrEqualTo(String value) {
            addCriterion("orgLinkTel >=", value, "orglinktel");
            return (Criteria) this;
        }

        public Criteria andOrglinktelLessThan(String value) {
            addCriterion("orgLinkTel <", value, "orglinktel");
            return (Criteria) this;
        }

        public Criteria andOrglinktelLessThanOrEqualTo(String value) {
            addCriterion("orgLinkTel <=", value, "orglinktel");
            return (Criteria) this;
        }

        public Criteria andOrglinktelLike(String value) {
            addCriterion("orgLinkTel like", value, "orglinktel");
            return (Criteria) this;
        }

        public Criteria andOrglinktelNotLike(String value) {
            addCriterion("orgLinkTel not like", value, "orglinktel");
            return (Criteria) this;
        }

        public Criteria andOrglinktelIn(List<String> values) {
            addCriterion("orgLinkTel in", values, "orglinktel");
            return (Criteria) this;
        }

        public Criteria andOrglinktelNotIn(List<String> values) {
            addCriterion("orgLinkTel not in", values, "orglinktel");
            return (Criteria) this;
        }

        public Criteria andOrglinktelBetween(String value1, String value2) {
            addCriterion("orgLinkTel between", value1, value2, "orglinktel");
            return (Criteria) this;
        }

        public Criteria andOrglinktelNotBetween(String value1, String value2) {
            addCriterion("orgLinkTel not between", value1, value2, "orglinktel");
            return (Criteria) this;
        }

        public Criteria andCardpwdIsNull() {
            addCriterion("cardPwd is null");
            return (Criteria) this;
        }

        public Criteria andCardpwdIsNotNull() {
            addCriterion("cardPwd is not null");
            return (Criteria) this;
        }

        public Criteria andCardpwdEqualTo(String value) {
            addCriterion("cardPwd =", value, "cardpwd");
            return (Criteria) this;
        }

        public Criteria andCardpwdNotEqualTo(String value) {
            addCriterion("cardPwd <>", value, "cardpwd");
            return (Criteria) this;
        }

        public Criteria andCardpwdGreaterThan(String value) {
            addCriterion("cardPwd >", value, "cardpwd");
            return (Criteria) this;
        }

        public Criteria andCardpwdGreaterThanOrEqualTo(String value) {
            addCriterion("cardPwd >=", value, "cardpwd");
            return (Criteria) this;
        }

        public Criteria andCardpwdLessThan(String value) {
            addCriterion("cardPwd <", value, "cardpwd");
            return (Criteria) this;
        }

        public Criteria andCardpwdLessThanOrEqualTo(String value) {
            addCriterion("cardPwd <=", value, "cardpwd");
            return (Criteria) this;
        }

        public Criteria andCardpwdLike(String value) {
            addCriterion("cardPwd like", value, "cardpwd");
            return (Criteria) this;
        }

        public Criteria andCardpwdNotLike(String value) {
            addCriterion("cardPwd not like", value, "cardpwd");
            return (Criteria) this;
        }

        public Criteria andCardpwdIn(List<String> values) {
            addCriterion("cardPwd in", values, "cardpwd");
            return (Criteria) this;
        }

        public Criteria andCardpwdNotIn(List<String> values) {
            addCriterion("cardPwd not in", values, "cardpwd");
            return (Criteria) this;
        }

        public Criteria andCardpwdBetween(String value1, String value2) {
            addCriterion("cardPwd between", value1, value2, "cardpwd");
            return (Criteria) this;
        }

        public Criteria andCardpwdNotBetween(String value1, String value2) {
            addCriterion("cardPwd not between", value1, value2, "cardpwd");
            return (Criteria) this;
        }

        public Criteria andElectricitypriceIsNull() {
            addCriterion("electricityPrice is null");
            return (Criteria) this;
        }

        public Criteria andElectricitypriceIsNotNull() {
            addCriterion("electricityPrice is not null");
            return (Criteria) this;
        }

        public Criteria andElectricitypriceEqualTo(Integer value) {
            addCriterion("electricityPrice =", value, "electricityprice");
            return (Criteria) this;
        }

        public Criteria andElectricitypriceNotEqualTo(Integer value) {
            addCriterion("electricityPrice <>", value, "electricityprice");
            return (Criteria) this;
        }

        public Criteria andElectricitypriceGreaterThan(Integer value) {
            addCriterion("electricityPrice >", value, "electricityprice");
            return (Criteria) this;
        }

        public Criteria andElectricitypriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("electricityPrice >=", value, "electricityprice");
            return (Criteria) this;
        }

        public Criteria andElectricitypriceLessThan(Integer value) {
            addCriterion("electricityPrice <", value, "electricityprice");
            return (Criteria) this;
        }

        public Criteria andElectricitypriceLessThanOrEqualTo(Integer value) {
            addCriterion("electricityPrice <=", value, "electricityprice");
            return (Criteria) this;
        }

        public Criteria andElectricitypriceIn(List<Integer> values) {
            addCriterion("electricityPrice in", values, "electricityprice");
            return (Criteria) this;
        }

        public Criteria andElectricitypriceNotIn(List<Integer> values) {
            addCriterion("electricityPrice not in", values, "electricityprice");
            return (Criteria) this;
        }

        public Criteria andElectricitypriceBetween(Integer value1, Integer value2) {
            addCriterion("electricityPrice between", value1, value2, "electricityprice");
            return (Criteria) this;
        }

        public Criteria andElectricitypriceNotBetween(Integer value1, Integer value2) {
            addCriterion("electricityPrice not between", value1, value2, "electricityprice");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNull() {
            addCriterion("createBy is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNotNull() {
            addCriterion("createBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyEqualTo(Integer value) {
            addCriterion("createBy =", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotEqualTo(Integer value) {
            addCriterion("createBy <>", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThan(Integer value) {
            addCriterion("createBy >", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThanOrEqualTo(Integer value) {
            addCriterion("createBy >=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThan(Integer value) {
            addCriterion("createBy <", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThanOrEqualTo(Integer value) {
            addCriterion("createBy <=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyIn(List<Integer> values) {
            addCriterion("createBy in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotIn(List<Integer> values) {
            addCriterion("createBy not in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyBetween(Integer value1, Integer value2) {
            addCriterion("createBy between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotBetween(Integer value1, Integer value2) {
            addCriterion("createBy not between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNull() {
            addCriterion("updateBy is null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNotNull() {
            addCriterion("updateBy is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyEqualTo(Integer value) {
            addCriterion("updateBy =", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotEqualTo(Integer value) {
            addCriterion("updateBy <>", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThan(Integer value) {
            addCriterion("updateBy >", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThanOrEqualTo(Integer value) {
            addCriterion("updateBy >=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThan(Integer value) {
            addCriterion("updateBy <", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThanOrEqualTo(Integer value) {
            addCriterion("updateBy <=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIn(List<Integer> values) {
            addCriterion("updateBy in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotIn(List<Integer> values) {
            addCriterion("updateBy not in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyBetween(Integer value1, Integer value2) {
            addCriterion("updateBy between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotBetween(Integer value1, Integer value2) {
            addCriterion("updateBy not between", value1, value2, "updateby");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ylk_org
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 20 11:48:01 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}