package com.ylk.datamineservice.model;

import java.util.Date;

public class CardInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card.id
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card.orgId
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Integer orgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card.custId
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Integer custid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card.cardNo
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private String cardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card.cardPwd
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private String cardpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card.money
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card.memo
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card.state
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card.deleted
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card.createTime
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card.updateTime
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card.createBy
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card.updateBy
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    private Integer updateby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card.id
     *
     * @return the value of ylk_card.id
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card.id
     *
     * @param id the value for ylk_card.id
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card.orgId
     *
     * @return the value of ylk_card.orgId
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Integer getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card.orgId
     *
     * @param orgid the value for ylk_card.orgId
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setOrgid(Integer orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card.custId
     *
     * @return the value of ylk_card.custId
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Integer getCustid() {
        return custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card.custId
     *
     * @param custid the value for ylk_card.custId
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setCustid(Integer custid) {
        this.custid = custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card.cardNo
     *
     * @return the value of ylk_card.cardNo
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card.cardNo
     *
     * @param cardno the value for ylk_card.cardNo
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setCardno(String cardno) {
        this.cardno = cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card.cardPwd
     *
     * @return the value of ylk_card.cardPwd
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public String getCardpwd() {
        return cardpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card.cardPwd
     *
     * @param cardpwd the value for ylk_card.cardPwd
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setCardpwd(String cardpwd) {
        this.cardpwd = cardpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card.money
     *
     * @return the value of ylk_card.money
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card.money
     *
     * @param money the value for ylk_card.money
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card.memo
     *
     * @return the value of ylk_card.memo
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card.memo
     *
     * @param memo the value for ylk_card.memo
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card.state
     *
     * @return the value of ylk_card.state
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card.state
     *
     * @param state the value for ylk_card.state
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card.deleted
     *
     * @return the value of ylk_card.deleted
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card.deleted
     *
     * @param deleted the value for ylk_card.deleted
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card.createTime
     *
     * @return the value of ylk_card.createTime
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card.createTime
     *
     * @param createtime the value for ylk_card.createTime
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card.updateTime
     *
     * @return the value of ylk_card.updateTime
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card.updateTime
     *
     * @param updatetime the value for ylk_card.updateTime
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card.createBy
     *
     * @return the value of ylk_card.createBy
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card.createBy
     *
     * @param createby the value for ylk_card.createBy
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card.updateBy
     *
     * @return the value of ylk_card.updateBy
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card.updateBy
     *
     * @param updateby the value for ylk_card.updateBy
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }
}