package com.ylk.datamineservice.model;

import java.util.Date;

public class CdzInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_cdz.id
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_cdz.orgId
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    private Integer orgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_cdz.cdzNo
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    private String cdzno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_cdz.cdzName
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    private String cdzname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_cdz.totalDegree
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    private Integer totaldegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_cdz.runState
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    private Integer runstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_cdz.workState
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    private Integer workstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_cdz.aGunState
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    private Integer agunstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_cdz.bGunState
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    private Integer bgunstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_cdz.memo
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_cdz.state
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_cdz.deleted
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_cdz.createTime
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_cdz.updateTime
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_cdz.createBy
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_cdz.updateBy
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    private Integer updateby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_cdz.id
     *
     * @return the value of ylk_cdz.id
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_cdz.id
     *
     * @param id the value for ylk_cdz.id
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_cdz.orgId
     *
     * @return the value of ylk_cdz.orgId
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public Integer getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_cdz.orgId
     *
     * @param orgid the value for ylk_cdz.orgId
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public void setOrgid(Integer orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_cdz.cdzNo
     *
     * @return the value of ylk_cdz.cdzNo
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public String getCdzno() {
        return cdzno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_cdz.cdzNo
     *
     * @param cdzno the value for ylk_cdz.cdzNo
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public void setCdzno(String cdzno) {
        this.cdzno = cdzno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_cdz.cdzName
     *
     * @return the value of ylk_cdz.cdzName
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public String getCdzname() {
        return cdzname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_cdz.cdzName
     *
     * @param cdzname the value for ylk_cdz.cdzName
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public void setCdzname(String cdzname) {
        this.cdzname = cdzname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_cdz.totalDegree
     *
     * @return the value of ylk_cdz.totalDegree
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public Integer getTotaldegree() {
        return totaldegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_cdz.totalDegree
     *
     * @param totaldegree the value for ylk_cdz.totalDegree
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public void setTotaldegree(Integer totaldegree) {
        this.totaldegree = totaldegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_cdz.runState
     *
     * @return the value of ylk_cdz.runState
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public Integer getRunstate() {
        return runstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_cdz.runState
     *
     * @param runstate the value for ylk_cdz.runState
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public void setRunstate(Integer runstate) {
        this.runstate = runstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_cdz.workState
     *
     * @return the value of ylk_cdz.workState
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public Integer getWorkstate() {
        return workstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_cdz.workState
     *
     * @param workstate the value for ylk_cdz.workState
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public void setWorkstate(Integer workstate) {
        this.workstate = workstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_cdz.aGunState
     *
     * @return the value of ylk_cdz.aGunState
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public Integer getAgunstate() {
        return agunstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_cdz.aGunState
     *
     * @param agunstate the value for ylk_cdz.aGunState
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public void setAgunstate(Integer agunstate) {
        this.agunstate = agunstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_cdz.bGunState
     *
     * @return the value of ylk_cdz.bGunState
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public Integer getBgunstate() {
        return bgunstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_cdz.bGunState
     *
     * @param bgunstate the value for ylk_cdz.bGunState
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public void setBgunstate(Integer bgunstate) {
        this.bgunstate = bgunstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_cdz.memo
     *
     * @return the value of ylk_cdz.memo
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_cdz.memo
     *
     * @param memo the value for ylk_cdz.memo
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_cdz.state
     *
     * @return the value of ylk_cdz.state
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_cdz.state
     *
     * @param state the value for ylk_cdz.state
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_cdz.deleted
     *
     * @return the value of ylk_cdz.deleted
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_cdz.deleted
     *
     * @param deleted the value for ylk_cdz.deleted
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_cdz.createTime
     *
     * @return the value of ylk_cdz.createTime
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_cdz.createTime
     *
     * @param createtime the value for ylk_cdz.createTime
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_cdz.updateTime
     *
     * @return the value of ylk_cdz.updateTime
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_cdz.updateTime
     *
     * @param updatetime the value for ylk_cdz.updateTime
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_cdz.createBy
     *
     * @return the value of ylk_cdz.createBy
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_cdz.createBy
     *
     * @param createby the value for ylk_cdz.createBy
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_cdz.updateBy
     *
     * @return the value of ylk_cdz.updateBy
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_cdz.updateBy
     *
     * @param updateby the value for ylk_cdz.updateBy
     *
     * @mbggenerated Mon Jun 13 21:34:06 CST 2016
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }
}