package com.ylk.datamineservice.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CdzInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    public CdzInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrgidIsNull() {
            addCriterion("orgId is null");
            return (Criteria) this;
        }

        public Criteria andOrgidIsNotNull() {
            addCriterion("orgId is not null");
            return (Criteria) this;
        }

        public Criteria andOrgidEqualTo(Integer value) {
            addCriterion("orgId =", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotEqualTo(Integer value) {
            addCriterion("orgId <>", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidGreaterThan(Integer value) {
            addCriterion("orgId >", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidGreaterThanOrEqualTo(Integer value) {
            addCriterion("orgId >=", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLessThan(Integer value) {
            addCriterion("orgId <", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLessThanOrEqualTo(Integer value) {
            addCriterion("orgId <=", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidIn(List<Integer> values) {
            addCriterion("orgId in", values, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotIn(List<Integer> values) {
            addCriterion("orgId not in", values, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidBetween(Integer value1, Integer value2) {
            addCriterion("orgId between", value1, value2, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotBetween(Integer value1, Integer value2) {
            addCriterion("orgId not between", value1, value2, "orgid");
            return (Criteria) this;
        }

        public Criteria andCdznoIsNull() {
            addCriterion("cdzNo is null");
            return (Criteria) this;
        }

        public Criteria andCdznoIsNotNull() {
            addCriterion("cdzNo is not null");
            return (Criteria) this;
        }

        public Criteria andCdznoEqualTo(String value) {
            addCriterion("cdzNo =", value, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoNotEqualTo(String value) {
            addCriterion("cdzNo <>", value, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoGreaterThan(String value) {
            addCriterion("cdzNo >", value, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoGreaterThanOrEqualTo(String value) {
            addCriterion("cdzNo >=", value, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoLessThan(String value) {
            addCriterion("cdzNo <", value, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoLessThanOrEqualTo(String value) {
            addCriterion("cdzNo <=", value, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoLike(String value) {
            addCriterion("cdzNo like", value, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoNotLike(String value) {
            addCriterion("cdzNo not like", value, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoIn(List<String> values) {
            addCriterion("cdzNo in", values, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoNotIn(List<String> values) {
            addCriterion("cdzNo not in", values, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoBetween(String value1, String value2) {
            addCriterion("cdzNo between", value1, value2, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoNotBetween(String value1, String value2) {
            addCriterion("cdzNo not between", value1, value2, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznameIsNull() {
            addCriterion("cdzName is null");
            return (Criteria) this;
        }

        public Criteria andCdznameIsNotNull() {
            addCriterion("cdzName is not null");
            return (Criteria) this;
        }

        public Criteria andCdznameEqualTo(String value) {
            addCriterion("cdzName =", value, "cdzname");
            return (Criteria) this;
        }

        public Criteria andCdznameNotEqualTo(String value) {
            addCriterion("cdzName <>", value, "cdzname");
            return (Criteria) this;
        }

        public Criteria andCdznameGreaterThan(String value) {
            addCriterion("cdzName >", value, "cdzname");
            return (Criteria) this;
        }

        public Criteria andCdznameGreaterThanOrEqualTo(String value) {
            addCriterion("cdzName >=", value, "cdzname");
            return (Criteria) this;
        }

        public Criteria andCdznameLessThan(String value) {
            addCriterion("cdzName <", value, "cdzname");
            return (Criteria) this;
        }

        public Criteria andCdznameLessThanOrEqualTo(String value) {
            addCriterion("cdzName <=", value, "cdzname");
            return (Criteria) this;
        }

        public Criteria andCdznameLike(String value) {
            addCriterion("cdzName like", value, "cdzname");
            return (Criteria) this;
        }

        public Criteria andCdznameNotLike(String value) {
            addCriterion("cdzName not like", value, "cdzname");
            return (Criteria) this;
        }

        public Criteria andCdznameIn(List<String> values) {
            addCriterion("cdzName in", values, "cdzname");
            return (Criteria) this;
        }

        public Criteria andCdznameNotIn(List<String> values) {
            addCriterion("cdzName not in", values, "cdzname");
            return (Criteria) this;
        }

        public Criteria andCdznameBetween(String value1, String value2) {
            addCriterion("cdzName between", value1, value2, "cdzname");
            return (Criteria) this;
        }

        public Criteria andCdznameNotBetween(String value1, String value2) {
            addCriterion("cdzName not between", value1, value2, "cdzname");
            return (Criteria) this;
        }

        public Criteria andTotaldegreeIsNull() {
            addCriterion("totalDegree is null");
            return (Criteria) this;
        }

        public Criteria andTotaldegreeIsNotNull() {
            addCriterion("totalDegree is not null");
            return (Criteria) this;
        }

        public Criteria andTotaldegreeEqualTo(Integer value) {
            addCriterion("totalDegree =", value, "totaldegree");
            return (Criteria) this;
        }

        public Criteria andTotaldegreeNotEqualTo(Integer value) {
            addCriterion("totalDegree <>", value, "totaldegree");
            return (Criteria) this;
        }

        public Criteria andTotaldegreeGreaterThan(Integer value) {
            addCriterion("totalDegree >", value, "totaldegree");
            return (Criteria) this;
        }

        public Criteria andTotaldegreeGreaterThanOrEqualTo(Integer value) {
            addCriterion("totalDegree >=", value, "totaldegree");
            return (Criteria) this;
        }

        public Criteria andTotaldegreeLessThan(Integer value) {
            addCriterion("totalDegree <", value, "totaldegree");
            return (Criteria) this;
        }

        public Criteria andTotaldegreeLessThanOrEqualTo(Integer value) {
            addCriterion("totalDegree <=", value, "totaldegree");
            return (Criteria) this;
        }

        public Criteria andTotaldegreeIn(List<Integer> values) {
            addCriterion("totalDegree in", values, "totaldegree");
            return (Criteria) this;
        }

        public Criteria andTotaldegreeNotIn(List<Integer> values) {
            addCriterion("totalDegree not in", values, "totaldegree");
            return (Criteria) this;
        }

        public Criteria andTotaldegreeBetween(Integer value1, Integer value2) {
            addCriterion("totalDegree between", value1, value2, "totaldegree");
            return (Criteria) this;
        }

        public Criteria andTotaldegreeNotBetween(Integer value1, Integer value2) {
            addCriterion("totalDegree not between", value1, value2, "totaldegree");
            return (Criteria) this;
        }

        public Criteria andRunstateIsNull() {
            addCriterion("runState is null");
            return (Criteria) this;
        }

        public Criteria andRunstateIsNotNull() {
            addCriterion("runState is not null");
            return (Criteria) this;
        }

        public Criteria andRunstateEqualTo(Integer value) {
            addCriterion("runState =", value, "runstate");
            return (Criteria) this;
        }

        public Criteria andRunstateNotEqualTo(Integer value) {
            addCriterion("runState <>", value, "runstate");
            return (Criteria) this;
        }

        public Criteria andRunstateGreaterThan(Integer value) {
            addCriterion("runState >", value, "runstate");
            return (Criteria) this;
        }

        public Criteria andRunstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("runState >=", value, "runstate");
            return (Criteria) this;
        }

        public Criteria andRunstateLessThan(Integer value) {
            addCriterion("runState <", value, "runstate");
            return (Criteria) this;
        }

        public Criteria andRunstateLessThanOrEqualTo(Integer value) {
            addCriterion("runState <=", value, "runstate");
            return (Criteria) this;
        }

        public Criteria andRunstateIn(List<Integer> values) {
            addCriterion("runState in", values, "runstate");
            return (Criteria) this;
        }

        public Criteria andRunstateNotIn(List<Integer> values) {
            addCriterion("runState not in", values, "runstate");
            return (Criteria) this;
        }

        public Criteria andRunstateBetween(Integer value1, Integer value2) {
            addCriterion("runState between", value1, value2, "runstate");
            return (Criteria) this;
        }

        public Criteria andRunstateNotBetween(Integer value1, Integer value2) {
            addCriterion("runState not between", value1, value2, "runstate");
            return (Criteria) this;
        }

        public Criteria andWorkstateIsNull() {
            addCriterion("workState is null");
            return (Criteria) this;
        }

        public Criteria andWorkstateIsNotNull() {
            addCriterion("workState is not null");
            return (Criteria) this;
        }

        public Criteria andWorkstateEqualTo(Integer value) {
            addCriterion("workState =", value, "workstate");
            return (Criteria) this;
        }

        public Criteria andWorkstateNotEqualTo(Integer value) {
            addCriterion("workState <>", value, "workstate");
            return (Criteria) this;
        }

        public Criteria andWorkstateGreaterThan(Integer value) {
            addCriterion("workState >", value, "workstate");
            return (Criteria) this;
        }

        public Criteria andWorkstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("workState >=", value, "workstate");
            return (Criteria) this;
        }

        public Criteria andWorkstateLessThan(Integer value) {
            addCriterion("workState <", value, "workstate");
            return (Criteria) this;
        }

        public Criteria andWorkstateLessThanOrEqualTo(Integer value) {
            addCriterion("workState <=", value, "workstate");
            return (Criteria) this;
        }

        public Criteria andWorkstateIn(List<Integer> values) {
            addCriterion("workState in", values, "workstate");
            return (Criteria) this;
        }

        public Criteria andWorkstateNotIn(List<Integer> values) {
            addCriterion("workState not in", values, "workstate");
            return (Criteria) this;
        }

        public Criteria andWorkstateBetween(Integer value1, Integer value2) {
            addCriterion("workState between", value1, value2, "workstate");
            return (Criteria) this;
        }

        public Criteria andWorkstateNotBetween(Integer value1, Integer value2) {
            addCriterion("workState not between", value1, value2, "workstate");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNull() {
            addCriterion("createBy is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNotNull() {
            addCriterion("createBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyEqualTo(Integer value) {
            addCriterion("createBy =", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotEqualTo(Integer value) {
            addCriterion("createBy <>", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThan(Integer value) {
            addCriterion("createBy >", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThanOrEqualTo(Integer value) {
            addCriterion("createBy >=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThan(Integer value) {
            addCriterion("createBy <", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThanOrEqualTo(Integer value) {
            addCriterion("createBy <=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyIn(List<Integer> values) {
            addCriterion("createBy in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotIn(List<Integer> values) {
            addCriterion("createBy not in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyBetween(Integer value1, Integer value2) {
            addCriterion("createBy between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotBetween(Integer value1, Integer value2) {
            addCriterion("createBy not between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNull() {
            addCriterion("updateBy is null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNotNull() {
            addCriterion("updateBy is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyEqualTo(Integer value) {
            addCriterion("updateBy =", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotEqualTo(Integer value) {
            addCriterion("updateBy <>", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThan(Integer value) {
            addCriterion("updateBy >", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThanOrEqualTo(Integer value) {
            addCriterion("updateBy >=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThan(Integer value) {
            addCriterion("updateBy <", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThanOrEqualTo(Integer value) {
            addCriterion("updateBy <=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIn(List<Integer> values) {
            addCriterion("updateBy in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotIn(List<Integer> values) {
            addCriterion("updateBy not in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyBetween(Integer value1, Integer value2) {
            addCriterion("updateBy between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotBetween(Integer value1, Integer value2) {
            addCriterion("updateBy not between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andModulenoIsNull() {
            addCriterion("moduleNo is null");
            return (Criteria) this;
        }

        public Criteria andModulenoIsNotNull() {
            addCriterion("moduleNo is not null");
            return (Criteria) this;
        }

        public Criteria andModulenoEqualTo(String value) {
            addCriterion("moduleNo =", value, "moduleno");
            return (Criteria) this;
        }

        public Criteria andModulenoNotEqualTo(String value) {
            addCriterion("moduleNo <>", value, "moduleno");
            return (Criteria) this;
        }

        public Criteria andModulenoGreaterThan(String value) {
            addCriterion("moduleNo >", value, "moduleno");
            return (Criteria) this;
        }

        public Criteria andModulenoGreaterThanOrEqualTo(String value) {
            addCriterion("moduleNo >=", value, "moduleno");
            return (Criteria) this;
        }

        public Criteria andModulenoLessThan(String value) {
            addCriterion("moduleNo <", value, "moduleno");
            return (Criteria) this;
        }

        public Criteria andModulenoLessThanOrEqualTo(String value) {
            addCriterion("moduleNo <=", value, "moduleno");
            return (Criteria) this;
        }

        public Criteria andModulenoLike(String value) {
            addCriterion("moduleNo like", value, "moduleno");
            return (Criteria) this;
        }

        public Criteria andModulenoNotLike(String value) {
            addCriterion("moduleNo not like", value, "moduleno");
            return (Criteria) this;
        }

        public Criteria andModulenoIn(List<String> values) {
            addCriterion("moduleNo in", values, "moduleno");
            return (Criteria) this;
        }

        public Criteria andModulenoNotIn(List<String> values) {
            addCriterion("moduleNo not in", values, "moduleno");
            return (Criteria) this;
        }

        public Criteria andModulenoBetween(String value1, String value2) {
            addCriterion("moduleNo between", value1, value2, "moduleno");
            return (Criteria) this;
        }

        public Criteria andModulenoNotBetween(String value1, String value2) {
            addCriterion("moduleNo not between", value1, value2, "moduleno");
            return (Criteria) this;
        }

        public Criteria andDevicenoIsNull() {
            addCriterion("deviceNo is null");
            return (Criteria) this;
        }

        public Criteria andDevicenoIsNotNull() {
            addCriterion("deviceNo is not null");
            return (Criteria) this;
        }

        public Criteria andDevicenoEqualTo(String value) {
            addCriterion("deviceNo =", value, "deviceno");
            return (Criteria) this;
        }

        public Criteria andDevicenoNotEqualTo(String value) {
            addCriterion("deviceNo <>", value, "deviceno");
            return (Criteria) this;
        }

        public Criteria andDevicenoGreaterThan(String value) {
            addCriterion("deviceNo >", value, "deviceno");
            return (Criteria) this;
        }

        public Criteria andDevicenoGreaterThanOrEqualTo(String value) {
            addCriterion("deviceNo >=", value, "deviceno");
            return (Criteria) this;
        }

        public Criteria andDevicenoLessThan(String value) {
            addCriterion("deviceNo <", value, "deviceno");
            return (Criteria) this;
        }

        public Criteria andDevicenoLessThanOrEqualTo(String value) {
            addCriterion("deviceNo <=", value, "deviceno");
            return (Criteria) this;
        }

        public Criteria andDevicenoLike(String value) {
            addCriterion("deviceNo like", value, "deviceno");
            return (Criteria) this;
        }

        public Criteria andDevicenoNotLike(String value) {
            addCriterion("deviceNo not like", value, "deviceno");
            return (Criteria) this;
        }

        public Criteria andDevicenoIn(List<String> values) {
            addCriterion("deviceNo in", values, "deviceno");
            return (Criteria) this;
        }

        public Criteria andDevicenoNotIn(List<String> values) {
            addCriterion("deviceNo not in", values, "deviceno");
            return (Criteria) this;
        }

        public Criteria andDevicenoBetween(String value1, String value2) {
            addCriterion("deviceNo between", value1, value2, "deviceno");
            return (Criteria) this;
        }

        public Criteria andDevicenoNotBetween(String value1, String value2) {
            addCriterion("deviceNo not between", value1, value2, "deviceno");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ylk_cdz
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 16 20:43:01 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}