package com.ylk.datamineservice.model;

import java.util.Date;

public class ChargeLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_charge_log.id
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_charge_log.charge_time
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    private Integer chargeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_charge_log.card_no
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    private Integer cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_charge_log.cdz_id
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    private Integer cdzId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_charge_log.amount
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_charge_log.begin_meter_qua
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    private Integer beginMeterQua;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_charge_log.begin_time
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_charge_log.end_meter_qua
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    private Integer endMeterQua;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_charge_log.end_time
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_charge_log.real_qua
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    private Integer realQua;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_charge_log.create_date
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_charge_log.state
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_charge_log.charge_type
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    private Integer chargeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_charge_log.data_type
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    private Integer dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_charge_log.memo
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_charge_log.id
     *
     * @return the value of ylk_charge_log.id
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_charge_log.id
     *
     * @param id the value for ylk_charge_log.id
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_charge_log.charge_time
     *
     * @return the value of ylk_charge_log.charge_time
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public Integer getChargeTime() {
        return chargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_charge_log.charge_time
     *
     * @param chargeTime the value for ylk_charge_log.charge_time
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public void setChargeTime(Integer chargeTime) {
        this.chargeTime = chargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_charge_log.card_no
     *
     * @return the value of ylk_charge_log.card_no
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public Integer getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_charge_log.card_no
     *
     * @param cardNo the value for ylk_charge_log.card_no
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public void setCardNo(Integer cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_charge_log.cdz_id
     *
     * @return the value of ylk_charge_log.cdz_id
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public Integer getCdzId() {
        return cdzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_charge_log.cdz_id
     *
     * @param cdzId the value for ylk_charge_log.cdz_id
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public void setCdzId(Integer cdzId) {
        this.cdzId = cdzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_charge_log.amount
     *
     * @return the value of ylk_charge_log.amount
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_charge_log.amount
     *
     * @param amount the value for ylk_charge_log.amount
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_charge_log.begin_meter_qua
     *
     * @return the value of ylk_charge_log.begin_meter_qua
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public Integer getBeginMeterQua() {
        return beginMeterQua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_charge_log.begin_meter_qua
     *
     * @param beginMeterQua the value for ylk_charge_log.begin_meter_qua
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public void setBeginMeterQua(Integer beginMeterQua) {
        this.beginMeterQua = beginMeterQua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_charge_log.begin_time
     *
     * @return the value of ylk_charge_log.begin_time
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_charge_log.begin_time
     *
     * @param beginTime the value for ylk_charge_log.begin_time
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_charge_log.end_meter_qua
     *
     * @return the value of ylk_charge_log.end_meter_qua
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public Integer getEndMeterQua() {
        return endMeterQua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_charge_log.end_meter_qua
     *
     * @param endMeterQua the value for ylk_charge_log.end_meter_qua
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public void setEndMeterQua(Integer endMeterQua) {
        this.endMeterQua = endMeterQua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_charge_log.end_time
     *
     * @return the value of ylk_charge_log.end_time
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_charge_log.end_time
     *
     * @param endTime the value for ylk_charge_log.end_time
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_charge_log.real_qua
     *
     * @return the value of ylk_charge_log.real_qua
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public Integer getRealQua() {
        return realQua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_charge_log.real_qua
     *
     * @param realQua the value for ylk_charge_log.real_qua
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public void setRealQua(Integer realQua) {
        this.realQua = realQua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_charge_log.create_date
     *
     * @return the value of ylk_charge_log.create_date
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_charge_log.create_date
     *
     * @param createDate the value for ylk_charge_log.create_date
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_charge_log.state
     *
     * @return the value of ylk_charge_log.state
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_charge_log.state
     *
     * @param state the value for ylk_charge_log.state
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_charge_log.charge_type
     *
     * @return the value of ylk_charge_log.charge_type
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public Integer getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_charge_log.charge_type
     *
     * @param chargeType the value for ylk_charge_log.charge_type
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public void setChargeType(Integer chargeType) {
        this.chargeType = chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_charge_log.data_type
     *
     * @return the value of ylk_charge_log.data_type
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_charge_log.data_type
     *
     * @param dataType the value for ylk_charge_log.data_type
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_charge_log.memo
     *
     * @return the value of ylk_charge_log.memo
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_charge_log.memo
     *
     * @param memo the value for ylk_charge_log.memo
     *
     * @mbggenerated Fri Jan 22 16:45:04 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }
}