package com.ylk.datamineservice.model;

import java.util.Date;

public class ChargeLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_charge_log.id
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_charge_log.charge_time
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    private Long chargeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_charge_log.card_no
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    private Integer cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_charge_log.cdz_id
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    private Long cdzId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_charge_log.amount
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_charge_log.charge_quantity
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    private Long chargeQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_charge_log.create_date
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_charge_log.state
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_charge_log.charge_type
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    private Integer chargeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_charge_log.gun_type
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    private String gunType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_charge_log.id
     *
     * @return the value of tbl_charge_log.id
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_charge_log.id
     *
     * @param id the value for tbl_charge_log.id
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_charge_log.charge_time
     *
     * @return the value of tbl_charge_log.charge_time
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public Long getChargeTime() {
        return chargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_charge_log.charge_time
     *
     * @param chargeTime the value for tbl_charge_log.charge_time
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public void setChargeTime(Long chargeTime) {
        this.chargeTime = chargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_charge_log.card_no
     *
     * @return the value of tbl_charge_log.card_no
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public Integer getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_charge_log.card_no
     *
     * @param cardNo the value for tbl_charge_log.card_no
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public void setCardNo(Integer cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_charge_log.cdz_id
     *
     * @return the value of tbl_charge_log.cdz_id
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public Long getCdzId() {
        return cdzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_charge_log.cdz_id
     *
     * @param cdzId the value for tbl_charge_log.cdz_id
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public void setCdzId(Long cdzId) {
        this.cdzId = cdzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_charge_log.amount
     *
     * @return the value of tbl_charge_log.amount
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_charge_log.amount
     *
     * @param amount the value for tbl_charge_log.amount
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_charge_log.charge_quantity
     *
     * @return the value of tbl_charge_log.charge_quantity
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public Long getChargeQuantity() {
        return chargeQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_charge_log.charge_quantity
     *
     * @param chargeQuantity the value for tbl_charge_log.charge_quantity
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public void setChargeQuantity(Long chargeQuantity) {
        this.chargeQuantity = chargeQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_charge_log.create_date
     *
     * @return the value of tbl_charge_log.create_date
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_charge_log.create_date
     *
     * @param createDate the value for tbl_charge_log.create_date
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_charge_log.state
     *
     * @return the value of tbl_charge_log.state
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_charge_log.state
     *
     * @param state the value for tbl_charge_log.state
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_charge_log.charge_type
     *
     * @return the value of tbl_charge_log.charge_type
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public Integer getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_charge_log.charge_type
     *
     * @param chargeType the value for tbl_charge_log.charge_type
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public void setChargeType(Integer chargeType) {
        this.chargeType = chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_charge_log.gun_type
     *
     * @return the value of tbl_charge_log.gun_type
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public String getGunType() {
        return gunType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_charge_log.gun_type
     *
     * @param gunType the value for tbl_charge_log.gun_type
     *
     * @mbggenerated Sun Jun 12 22:50:36 CST 2016
     */
    public void setGunType(String gunType) {
        this.gunType = gunType;
    }
}