package com.ylk.datamineservice.model;

import java.util.Date;

public class ModuleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.id
     *
     * @mbggenerated Sat Jun 18 21:38:00 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.module_no
     *
     * @mbggenerated Sat Jun 18 21:38:00 CST 2016
     */
    private String moduleNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.ip
     *
     * @mbggenerated Sat Jun 18 21:38:00 CST 2016
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.createTime
     *
     * @mbggenerated Sat Jun 18 21:38:00 CST 2016
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.id
     *
     * @return the value of tbl_module.id
     *
     * @mbggenerated Sat Jun 18 21:38:00 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.id
     *
     * @param id the value for tbl_module.id
     *
     * @mbggenerated Sat Jun 18 21:38:00 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.module_no
     *
     * @return the value of tbl_module.module_no
     *
     * @mbggenerated Sat Jun 18 21:38:00 CST 2016
     */
    public String getModuleNo() {
        return moduleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.module_no
     *
     * @param moduleNo the value for tbl_module.module_no
     *
     * @mbggenerated Sat Jun 18 21:38:00 CST 2016
     */
    public void setModuleNo(String moduleNo) {
        this.moduleNo = moduleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.ip
     *
     * @return the value of tbl_module.ip
     *
     * @mbggenerated Sat Jun 18 21:38:00 CST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.ip
     *
     * @param ip the value for tbl_module.ip
     *
     * @mbggenerated Sat Jun 18 21:38:00 CST 2016
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.createTime
     *
     * @return the value of tbl_module.createTime
     *
     * @mbggenerated Sat Jun 18 21:38:00 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.createTime
     *
     * @param createtime the value for tbl_module.createTime
     *
     * @mbggenerated Sat Jun 18 21:38:00 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}