package com.ylk.datamineservice.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StreamInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public StreamInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCardnoIsNull() {
            addCriterion("cardNo is null");
            return (Criteria) this;
        }

        public Criteria andCardnoIsNotNull() {
            addCriterion("cardNo is not null");
            return (Criteria) this;
        }

        public Criteria andCardnoEqualTo(String value) {
            addCriterion("cardNo =", value, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoNotEqualTo(String value) {
            addCriterion("cardNo <>", value, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoGreaterThan(String value) {
            addCriterion("cardNo >", value, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoGreaterThanOrEqualTo(String value) {
            addCriterion("cardNo >=", value, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoLessThan(String value) {
            addCriterion("cardNo <", value, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoLessThanOrEqualTo(String value) {
            addCriterion("cardNo <=", value, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoLike(String value) {
            addCriterion("cardNo like", value, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoNotLike(String value) {
            addCriterion("cardNo not like", value, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoIn(List<String> values) {
            addCriterion("cardNo in", values, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoNotIn(List<String> values) {
            addCriterion("cardNo not in", values, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoBetween(String value1, String value2) {
            addCriterion("cardNo between", value1, value2, "cardno");
            return (Criteria) this;
        }

        public Criteria andCardnoNotBetween(String value1, String value2) {
            addCriterion("cardNo not between", value1, value2, "cardno");
            return (Criteria) this;
        }

        public Criteria andChangetypeIsNull() {
            addCriterion("changeType is null");
            return (Criteria) this;
        }

        public Criteria andChangetypeIsNotNull() {
            addCriterion("changeType is not null");
            return (Criteria) this;
        }

        public Criteria andChangetypeEqualTo(Integer value) {
            addCriterion("changeType =", value, "changetype");
            return (Criteria) this;
        }

        public Criteria andChangetypeNotEqualTo(Integer value) {
            addCriterion("changeType <>", value, "changetype");
            return (Criteria) this;
        }

        public Criteria andChangetypeGreaterThan(Integer value) {
            addCriterion("changeType >", value, "changetype");
            return (Criteria) this;
        }

        public Criteria andChangetypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("changeType >=", value, "changetype");
            return (Criteria) this;
        }

        public Criteria andChangetypeLessThan(Integer value) {
            addCriterion("changeType <", value, "changetype");
            return (Criteria) this;
        }

        public Criteria andChangetypeLessThanOrEqualTo(Integer value) {
            addCriterion("changeType <=", value, "changetype");
            return (Criteria) this;
        }

        public Criteria andChangetypeIn(List<Integer> values) {
            addCriterion("changeType in", values, "changetype");
            return (Criteria) this;
        }

        public Criteria andChangetypeNotIn(List<Integer> values) {
            addCriterion("changeType not in", values, "changetype");
            return (Criteria) this;
        }

        public Criteria andChangetypeBetween(Integer value1, Integer value2) {
            addCriterion("changeType between", value1, value2, "changetype");
            return (Criteria) this;
        }

        public Criteria andChangetypeNotBetween(Integer value1, Integer value2) {
            addCriterion("changeType not between", value1, value2, "changetype");
            return (Criteria) this;
        }

        public Criteria andFundchangeIsNull() {
            addCriterion("fundChange is null");
            return (Criteria) this;
        }

        public Criteria andFundchangeIsNotNull() {
            addCriterion("fundChange is not null");
            return (Criteria) this;
        }

        public Criteria andFundchangeEqualTo(Integer value) {
            addCriterion("fundChange =", value, "fundchange");
            return (Criteria) this;
        }

        public Criteria andFundchangeNotEqualTo(Integer value) {
            addCriterion("fundChange <>", value, "fundchange");
            return (Criteria) this;
        }

        public Criteria andFundchangeGreaterThan(Integer value) {
            addCriterion("fundChange >", value, "fundchange");
            return (Criteria) this;
        }

        public Criteria andFundchangeGreaterThanOrEqualTo(Integer value) {
            addCriterion("fundChange >=", value, "fundchange");
            return (Criteria) this;
        }

        public Criteria andFundchangeLessThan(Integer value) {
            addCriterion("fundChange <", value, "fundchange");
            return (Criteria) this;
        }

        public Criteria andFundchangeLessThanOrEqualTo(Integer value) {
            addCriterion("fundChange <=", value, "fundchange");
            return (Criteria) this;
        }

        public Criteria andFundchangeIn(List<Integer> values) {
            addCriterion("fundChange in", values, "fundchange");
            return (Criteria) this;
        }

        public Criteria andFundchangeNotIn(List<Integer> values) {
            addCriterion("fundChange not in", values, "fundchange");
            return (Criteria) this;
        }

        public Criteria andFundchangeBetween(Integer value1, Integer value2) {
            addCriterion("fundChange between", value1, value2, "fundchange");
            return (Criteria) this;
        }

        public Criteria andFundchangeNotBetween(Integer value1, Integer value2) {
            addCriterion("fundChange not between", value1, value2, "fundchange");
            return (Criteria) this;
        }

        public Criteria andFundoldIsNull() {
            addCriterion("fundOld is null");
            return (Criteria) this;
        }

        public Criteria andFundoldIsNotNull() {
            addCriterion("fundOld is not null");
            return (Criteria) this;
        }

        public Criteria andFundoldEqualTo(Integer value) {
            addCriterion("fundOld =", value, "fundold");
            return (Criteria) this;
        }

        public Criteria andFundoldNotEqualTo(Integer value) {
            addCriterion("fundOld <>", value, "fundold");
            return (Criteria) this;
        }

        public Criteria andFundoldGreaterThan(Integer value) {
            addCriterion("fundOld >", value, "fundold");
            return (Criteria) this;
        }

        public Criteria andFundoldGreaterThanOrEqualTo(Integer value) {
            addCriterion("fundOld >=", value, "fundold");
            return (Criteria) this;
        }

        public Criteria andFundoldLessThan(Integer value) {
            addCriterion("fundOld <", value, "fundold");
            return (Criteria) this;
        }

        public Criteria andFundoldLessThanOrEqualTo(Integer value) {
            addCriterion("fundOld <=", value, "fundold");
            return (Criteria) this;
        }

        public Criteria andFundoldIn(List<Integer> values) {
            addCriterion("fundOld in", values, "fundold");
            return (Criteria) this;
        }

        public Criteria andFundoldNotIn(List<Integer> values) {
            addCriterion("fundOld not in", values, "fundold");
            return (Criteria) this;
        }

        public Criteria andFundoldBetween(Integer value1, Integer value2) {
            addCriterion("fundOld between", value1, value2, "fundold");
            return (Criteria) this;
        }

        public Criteria andFundoldNotBetween(Integer value1, Integer value2) {
            addCriterion("fundOld not between", value1, value2, "fundold");
            return (Criteria) this;
        }

        public Criteria andFundnewIsNull() {
            addCriterion("fundNew is null");
            return (Criteria) this;
        }

        public Criteria andFundnewIsNotNull() {
            addCriterion("fundNew is not null");
            return (Criteria) this;
        }

        public Criteria andFundnewEqualTo(Integer value) {
            addCriterion("fundNew =", value, "fundnew");
            return (Criteria) this;
        }

        public Criteria andFundnewNotEqualTo(Integer value) {
            addCriterion("fundNew <>", value, "fundnew");
            return (Criteria) this;
        }

        public Criteria andFundnewGreaterThan(Integer value) {
            addCriterion("fundNew >", value, "fundnew");
            return (Criteria) this;
        }

        public Criteria andFundnewGreaterThanOrEqualTo(Integer value) {
            addCriterion("fundNew >=", value, "fundnew");
            return (Criteria) this;
        }

        public Criteria andFundnewLessThan(Integer value) {
            addCriterion("fundNew <", value, "fundnew");
            return (Criteria) this;
        }

        public Criteria andFundnewLessThanOrEqualTo(Integer value) {
            addCriterion("fundNew <=", value, "fundnew");
            return (Criteria) this;
        }

        public Criteria andFundnewIn(List<Integer> values) {
            addCriterion("fundNew in", values, "fundnew");
            return (Criteria) this;
        }

        public Criteria andFundnewNotIn(List<Integer> values) {
            addCriterion("fundNew not in", values, "fundnew");
            return (Criteria) this;
        }

        public Criteria andFundnewBetween(Integer value1, Integer value2) {
            addCriterion("fundNew between", value1, value2, "fundnew");
            return (Criteria) this;
        }

        public Criteria andFundnewNotBetween(Integer value1, Integer value2) {
            addCriterion("fundNew not between", value1, value2, "fundnew");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Integer> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Integer> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andDegreeIsNull() {
            addCriterion("degree is null");
            return (Criteria) this;
        }

        public Criteria andDegreeIsNotNull() {
            addCriterion("degree is not null");
            return (Criteria) this;
        }

        public Criteria andDegreeEqualTo(Integer value) {
            addCriterion("degree =", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeNotEqualTo(Integer value) {
            addCriterion("degree <>", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeGreaterThan(Integer value) {
            addCriterion("degree >", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeGreaterThanOrEqualTo(Integer value) {
            addCriterion("degree >=", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeLessThan(Integer value) {
            addCriterion("degree <", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeLessThanOrEqualTo(Integer value) {
            addCriterion("degree <=", value, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeIn(List<Integer> values) {
            addCriterion("degree in", values, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeNotIn(List<Integer> values) {
            addCriterion("degree not in", values, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeBetween(Integer value1, Integer value2) {
            addCriterion("degree between", value1, value2, "degree");
            return (Criteria) this;
        }

        public Criteria andDegreeNotBetween(Integer value1, Integer value2) {
            addCriterion("degree not between", value1, value2, "degree");
            return (Criteria) this;
        }

        public Criteria andCdznoIsNull() {
            addCriterion("cdzNo is null");
            return (Criteria) this;
        }

        public Criteria andCdznoIsNotNull() {
            addCriterion("cdzNo is not null");
            return (Criteria) this;
        }

        public Criteria andCdznoEqualTo(String value) {
            addCriterion("cdzNo =", value, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoNotEqualTo(String value) {
            addCriterion("cdzNo <>", value, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoGreaterThan(String value) {
            addCriterion("cdzNo >", value, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoGreaterThanOrEqualTo(String value) {
            addCriterion("cdzNo >=", value, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoLessThan(String value) {
            addCriterion("cdzNo <", value, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoLessThanOrEqualTo(String value) {
            addCriterion("cdzNo <=", value, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoLike(String value) {
            addCriterion("cdzNo like", value, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoNotLike(String value) {
            addCriterion("cdzNo not like", value, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoIn(List<String> values) {
            addCriterion("cdzNo in", values, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoNotIn(List<String> values) {
            addCriterion("cdzNo not in", values, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoBetween(String value1, String value2) {
            addCriterion("cdzNo between", value1, value2, "cdzno");
            return (Criteria) this;
        }

        public Criteria andCdznoNotBetween(String value1, String value2) {
            addCriterion("cdzNo not between", value1, value2, "cdzno");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMeterquastartIsNull() {
            addCriterion("meterQuaStart is null");
            return (Criteria) this;
        }

        public Criteria andMeterquastartIsNotNull() {
            addCriterion("meterQuaStart is not null");
            return (Criteria) this;
        }

        public Criteria andMeterquastartEqualTo(Integer value) {
            addCriterion("meterQuaStart =", value, "meterquastart");
            return (Criteria) this;
        }

        public Criteria andMeterquastartNotEqualTo(Integer value) {
            addCriterion("meterQuaStart <>", value, "meterquastart");
            return (Criteria) this;
        }

        public Criteria andMeterquastartGreaterThan(Integer value) {
            addCriterion("meterQuaStart >", value, "meterquastart");
            return (Criteria) this;
        }

        public Criteria andMeterquastartGreaterThanOrEqualTo(Integer value) {
            addCriterion("meterQuaStart >=", value, "meterquastart");
            return (Criteria) this;
        }

        public Criteria andMeterquastartLessThan(Integer value) {
            addCriterion("meterQuaStart <", value, "meterquastart");
            return (Criteria) this;
        }

        public Criteria andMeterquastartLessThanOrEqualTo(Integer value) {
            addCriterion("meterQuaStart <=", value, "meterquastart");
            return (Criteria) this;
        }

        public Criteria andMeterquastartIn(List<Integer> values) {
            addCriterion("meterQuaStart in", values, "meterquastart");
            return (Criteria) this;
        }

        public Criteria andMeterquastartNotIn(List<Integer> values) {
            addCriterion("meterQuaStart not in", values, "meterquastart");
            return (Criteria) this;
        }

        public Criteria andMeterquastartBetween(Integer value1, Integer value2) {
            addCriterion("meterQuaStart between", value1, value2, "meterquastart");
            return (Criteria) this;
        }

        public Criteria andMeterquastartNotBetween(Integer value1, Integer value2) {
            addCriterion("meterQuaStart not between", value1, value2, "meterquastart");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNull() {
            addCriterion("startTime is null");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNotNull() {
            addCriterion("startTime is not null");
            return (Criteria) this;
        }

        public Criteria andStarttimeEqualTo(Date value) {
            addCriterion("startTime =", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotEqualTo(Date value) {
            addCriterion("startTime <>", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThan(Date value) {
            addCriterion("startTime >", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("startTime >=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThan(Date value) {
            addCriterion("startTime <", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThanOrEqualTo(Date value) {
            addCriterion("startTime <=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeIn(List<Date> values) {
            addCriterion("startTime in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotIn(List<Date> values) {
            addCriterion("startTime not in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeBetween(Date value1, Date value2) {
            addCriterion("startTime between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotBetween(Date value1, Date value2) {
            addCriterion("startTime not between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andMeterquaendIsNull() {
            addCriterion("meterQuaEnd is null");
            return (Criteria) this;
        }

        public Criteria andMeterquaendIsNotNull() {
            addCriterion("meterQuaEnd is not null");
            return (Criteria) this;
        }

        public Criteria andMeterquaendEqualTo(Integer value) {
            addCriterion("meterQuaEnd =", value, "meterquaend");
            return (Criteria) this;
        }

        public Criteria andMeterquaendNotEqualTo(Integer value) {
            addCriterion("meterQuaEnd <>", value, "meterquaend");
            return (Criteria) this;
        }

        public Criteria andMeterquaendGreaterThan(Integer value) {
            addCriterion("meterQuaEnd >", value, "meterquaend");
            return (Criteria) this;
        }

        public Criteria andMeterquaendGreaterThanOrEqualTo(Integer value) {
            addCriterion("meterQuaEnd >=", value, "meterquaend");
            return (Criteria) this;
        }

        public Criteria andMeterquaendLessThan(Integer value) {
            addCriterion("meterQuaEnd <", value, "meterquaend");
            return (Criteria) this;
        }

        public Criteria andMeterquaendLessThanOrEqualTo(Integer value) {
            addCriterion("meterQuaEnd <=", value, "meterquaend");
            return (Criteria) this;
        }

        public Criteria andMeterquaendIn(List<Integer> values) {
            addCriterion("meterQuaEnd in", values, "meterquaend");
            return (Criteria) this;
        }

        public Criteria andMeterquaendNotIn(List<Integer> values) {
            addCriterion("meterQuaEnd not in", values, "meterquaend");
            return (Criteria) this;
        }

        public Criteria andMeterquaendBetween(Integer value1, Integer value2) {
            addCriterion("meterQuaEnd between", value1, value2, "meterquaend");
            return (Criteria) this;
        }

        public Criteria andMeterquaendNotBetween(Integer value1, Integer value2) {
            addCriterion("meterQuaEnd not between", value1, value2, "meterquaend");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNull() {
            addCriterion("endTime is null");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNotNull() {
            addCriterion("endTime is not null");
            return (Criteria) this;
        }

        public Criteria andEndtimeEqualTo(Date value) {
            addCriterion("endTime =", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotEqualTo(Date value) {
            addCriterion("endTime <>", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThan(Date value) {
            addCriterion("endTime >", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("endTime >=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThan(Date value) {
            addCriterion("endTime <", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("endTime <=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIn(List<Date> values) {
            addCriterion("endTime in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotIn(List<Date> values) {
            addCriterion("endTime not in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeBetween(Date value1, Date value2) {
            addCriterion("endTime between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("endTime not between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNull() {
            addCriterion("createBy is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNotNull() {
            addCriterion("createBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyEqualTo(Integer value) {
            addCriterion("createBy =", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotEqualTo(Integer value) {
            addCriterion("createBy <>", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThan(Integer value) {
            addCriterion("createBy >", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThanOrEqualTo(Integer value) {
            addCriterion("createBy >=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThan(Integer value) {
            addCriterion("createBy <", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThanOrEqualTo(Integer value) {
            addCriterion("createBy <=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyIn(List<Integer> values) {
            addCriterion("createBy in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotIn(List<Integer> values) {
            addCriterion("createBy not in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyBetween(Integer value1, Integer value2) {
            addCriterion("createBy between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotBetween(Integer value1, Integer value2) {
            addCriterion("createBy not between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNull() {
            addCriterion("updateBy is null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNotNull() {
            addCriterion("updateBy is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyEqualTo(Integer value) {
            addCriterion("updateBy =", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotEqualTo(Integer value) {
            addCriterion("updateBy <>", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThan(Integer value) {
            addCriterion("updateBy >", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThanOrEqualTo(Integer value) {
            addCriterion("updateBy >=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThan(Integer value) {
            addCriterion("updateBy <", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThanOrEqualTo(Integer value) {
            addCriterion("updateBy <=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIn(List<Integer> values) {
            addCriterion("updateBy in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotIn(List<Integer> values) {
            addCriterion("updateBy not in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyBetween(Integer value1, Integer value2) {
            addCriterion("updateBy between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotBetween(Integer value1, Integer value2) {
            addCriterion("updateBy not between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andGuntypeIsNull() {
            addCriterion("gunType is null");
            return (Criteria) this;
        }

        public Criteria andGuntypeIsNotNull() {
            addCriterion("gunType is not null");
            return (Criteria) this;
        }

        public Criteria andGuntypeEqualTo(String value) {
            addCriterion("gunType =", value, "guntype");
            return (Criteria) this;
        }

        public Criteria andGuntypeNotEqualTo(String value) {
            addCriterion("gunType <>", value, "guntype");
            return (Criteria) this;
        }

        public Criteria andGuntypeGreaterThan(String value) {
            addCriterion("gunType >", value, "guntype");
            return (Criteria) this;
        }

        public Criteria andGuntypeGreaterThanOrEqualTo(String value) {
            addCriterion("gunType >=", value, "guntype");
            return (Criteria) this;
        }

        public Criteria andGuntypeLessThan(String value) {
            addCriterion("gunType <", value, "guntype");
            return (Criteria) this;
        }

        public Criteria andGuntypeLessThanOrEqualTo(String value) {
            addCriterion("gunType <=", value, "guntype");
            return (Criteria) this;
        }

        public Criteria andGuntypeLike(String value) {
            addCriterion("gunType like", value, "guntype");
            return (Criteria) this;
        }

        public Criteria andGuntypeNotLike(String value) {
            addCriterion("gunType not like", value, "guntype");
            return (Criteria) this;
        }

        public Criteria andGuntypeIn(List<String> values) {
            addCriterion("gunType in", values, "guntype");
            return (Criteria) this;
        }

        public Criteria andGuntypeNotIn(List<String> values) {
            addCriterion("gunType not in", values, "guntype");
            return (Criteria) this;
        }

        public Criteria andGuntypeBetween(String value1, String value2) {
            addCriterion("gunType between", value1, value2, "guntype");
            return (Criteria) this;
        }

        public Criteria andGuntypeNotBetween(String value1, String value2) {
            addCriterion("gunType not between", value1, value2, "guntype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ylk_card_stream
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 12 23:30:40 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}