package com.ylk.datamineservice.model;

import java.util.Date;

public class StreamInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.id
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.cardNo
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private String cardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.changeType
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Integer changetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.fundChange
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Integer fundchange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.fundOld
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Integer fundold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.fundNew
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Integer fundnew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.price
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.degree
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Integer degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.cdzNo
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private String cdzno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.memo
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.meterQuaStart
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Integer meterquastart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.startTime
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.meterQuaEnd
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Integer meterquaend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.endTime
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.state
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.deleted
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Integer deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.createTime
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.updateTime
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.createBy
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.updateBy
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ylk_card_stream.gunType
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    private String guntype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.id
     *
     * @return the value of ylk_card_stream.id
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.id
     *
     * @param id the value for ylk_card_stream.id
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.cardNo
     *
     * @return the value of ylk_card_stream.cardNo
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.cardNo
     *
     * @param cardno the value for ylk_card_stream.cardNo
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setCardno(String cardno) {
        this.cardno = cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.changeType
     *
     * @return the value of ylk_card_stream.changeType
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Integer getChangetype() {
        return changetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.changeType
     *
     * @param changetype the value for ylk_card_stream.changeType
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setChangetype(Integer changetype) {
        this.changetype = changetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.fundChange
     *
     * @return the value of ylk_card_stream.fundChange
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Integer getFundchange() {
        return fundchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.fundChange
     *
     * @param fundchange the value for ylk_card_stream.fundChange
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setFundchange(Integer fundchange) {
        this.fundchange = fundchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.fundOld
     *
     * @return the value of ylk_card_stream.fundOld
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Integer getFundold() {
        return fundold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.fundOld
     *
     * @param fundold the value for ylk_card_stream.fundOld
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setFundold(Integer fundold) {
        this.fundold = fundold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.fundNew
     *
     * @return the value of ylk_card_stream.fundNew
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Integer getFundnew() {
        return fundnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.fundNew
     *
     * @param fundnew the value for ylk_card_stream.fundNew
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setFundnew(Integer fundnew) {
        this.fundnew = fundnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.price
     *
     * @return the value of ylk_card_stream.price
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.price
     *
     * @param price the value for ylk_card_stream.price
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.degree
     *
     * @return the value of ylk_card_stream.degree
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Integer getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.degree
     *
     * @param degree the value for ylk_card_stream.degree
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setDegree(Integer degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.cdzNo
     *
     * @return the value of ylk_card_stream.cdzNo
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public String getCdzno() {
        return cdzno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.cdzNo
     *
     * @param cdzno the value for ylk_card_stream.cdzNo
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setCdzno(String cdzno) {
        this.cdzno = cdzno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.memo
     *
     * @return the value of ylk_card_stream.memo
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.memo
     *
     * @param memo the value for ylk_card_stream.memo
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.meterQuaStart
     *
     * @return the value of ylk_card_stream.meterQuaStart
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Integer getMeterquastart() {
        return meterquastart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.meterQuaStart
     *
     * @param meterquastart the value for ylk_card_stream.meterQuaStart
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setMeterquastart(Integer meterquastart) {
        this.meterquastart = meterquastart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.startTime
     *
     * @return the value of ylk_card_stream.startTime
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.startTime
     *
     * @param starttime the value for ylk_card_stream.startTime
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.meterQuaEnd
     *
     * @return the value of ylk_card_stream.meterQuaEnd
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Integer getMeterquaend() {
        return meterquaend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.meterQuaEnd
     *
     * @param meterquaend the value for ylk_card_stream.meterQuaEnd
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setMeterquaend(Integer meterquaend) {
        this.meterquaend = meterquaend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.endTime
     *
     * @return the value of ylk_card_stream.endTime
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.endTime
     *
     * @param endtime the value for ylk_card_stream.endTime
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.state
     *
     * @return the value of ylk_card_stream.state
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.state
     *
     * @param state the value for ylk_card_stream.state
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.deleted
     *
     * @return the value of ylk_card_stream.deleted
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.deleted
     *
     * @param deleted the value for ylk_card_stream.deleted
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.createTime
     *
     * @return the value of ylk_card_stream.createTime
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.createTime
     *
     * @param createtime the value for ylk_card_stream.createTime
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.updateTime
     *
     * @return the value of ylk_card_stream.updateTime
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.updateTime
     *
     * @param updatetime the value for ylk_card_stream.updateTime
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.createBy
     *
     * @return the value of ylk_card_stream.createBy
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.createBy
     *
     * @param createby the value for ylk_card_stream.createBy
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.updateBy
     *
     * @return the value of ylk_card_stream.updateBy
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.updateBy
     *
     * @param updateby the value for ylk_card_stream.updateBy
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ylk_card_stream.gunType
     *
     * @return the value of ylk_card_stream.gunType
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public String getGuntype() {
        return guntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ylk_card_stream.gunType
     *
     * @param guntype the value for ylk_card_stream.gunType
     *
     * @mbggenerated Sun Jun 12 23:30:40 CST 2016
     */
    public void setGuntype(String guntype) {
        this.guntype = guntype;
    }
}