package com.ylk.datamineservice.mapper;

import com.ylk.datamineservice.model.AreaInfo;
import com.ylk.datamineservice.model.AreaInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AreaInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    int countByExample(AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    int deleteByExample(AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    int insert(AreaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    int insertSelective(AreaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    List<AreaInfo> selectByExample(AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    AreaInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    int updateByExampleSelective(@Param("record") AreaInfo record, @Param("example") AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    int updateByExample(@Param("record") AreaInfo record, @Param("example") AreaInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    int updateByPrimaryKeySelective(AreaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_org
     *
     * @mbggenerated Wed Jan 20 11:48:01 CST 2016
     */
    int updateByPrimaryKey(AreaInfo record);
}