package com.ylk.datamineservice.mapper;

import com.ylk.datamineservice.model.CdzInfo;
import com.ylk.datamineservice.model.CdzInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CdzInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    int countByExample(CdzInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    int deleteByExample(CdzInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    int insert(CdzInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    int insertSelective(CdzInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    List<CdzInfo> selectByExample(CdzInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    CdzInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    int updateByExampleSelective(@Param("record") CdzInfo record, @Param("example") CdzInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    int updateByExample(@Param("record") CdzInfo record, @Param("example") CdzInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    int updateByPrimaryKeySelective(CdzInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_cdz
     *
     * @mbggenerated Sat Apr 16 20:43:01 CST 2016
     */
    int updateByPrimaryKey(CdzInfo record);
}