package com.ylk.datamineservice.mapper;

import com.ylk.datamineservice.model.StreamInfo;
import com.ylk.datamineservice.model.StreamInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StreamInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Fri Jan 22 16:32:46 CST 2016
     */
    int countByExample(StreamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Fri Jan 22 16:32:46 CST 2016
     */
    int deleteByExample(StreamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Fri Jan 22 16:32:46 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Fri Jan 22 16:32:46 CST 2016
     */
    int insert(StreamInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Fri Jan 22 16:32:46 CST 2016
     */
    int insertSelective(StreamInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Fri Jan 22 16:32:46 CST 2016
     */
    List<StreamInfo> selectByExample(StreamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Fri Jan 22 16:32:46 CST 2016
     */
    StreamInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Fri Jan 22 16:32:46 CST 2016
     */
    int updateByExampleSelective(@Param("record") StreamInfo record, @Param("example") StreamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Fri Jan 22 16:32:46 CST 2016
     */
    int updateByExample(@Param("record") StreamInfo record, @Param("example") StreamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Fri Jan 22 16:32:46 CST 2016
     */
    int updateByPrimaryKeySelective(StreamInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ylk_card_stream
     *
     * @mbggenerated Fri Jan 22 16:32:46 CST 2016
     */
    int updateByPrimaryKey(StreamInfo record);
}